### PR TITLE
AAP-11533 Add support for workload identity

### PR DESCRIPTION
**Pull request by bhavenst**
Add support for fetching token from workload identity auth system with fallback to pod identity.

Works fine w/ workload identity, test deployment to make sure it still works for non-workload identity in progress.

### CODE REVIEW

**Comment by bhavenst** [comment]
Tested in pod identity (current) deployment now and also works fine there, so good to go.

**Comment by bhavenst** [comment]
To test, make a marketplace deployment w/ billing enabled and create this pod below.  I just published under "Dev Test" aka plan10 in "Bryan Test" aka bhavensttest a package using workload identity, so you can deploy that one.  In order to actually do any billing, you need to run a number of hosts that is greater than the base quantity for the plan before running the billing code.  That is at least 3 hosts for this plan.

Plan:
https://portal.azure.com/#create/redhat1627408356675.bhavensttest-previewplan10

Manifest:

apiVersion: v1
kind: Pod
metadata:
  name: billing-test
  namespace: ansible-automation-platform-billing
  labels:
    azure.workload.identity/use: "true"
spec:
  containers:
  - name: billing
    image: quay.io/bhavenst/billing:latest
    command: ["/usr/bin/tail", "-f", "/dev/null"]
    volumeMounts:
    - mountPath: /etc/billing/billingconf.py
      name: billing-settings
      readOnly: true
      subPath: billingconf.py
  volumes:
  - name: billing-settings
    secret:
      defaultMode: 420
      secretName: billing-settings


Exec into the pod and run "aap-billing -d" to execute billing.

**Review by benjdudas — APPROVED** [review]

**Comment by benjdudas** [comment]
Looks good Bryan, thanks!

**Comment by sharvarikhedkar** [comment]
@bhavenst this is the expected result right? testing on a [internal monthly offer](https://portal.azure.com/#@RHAAP.onmicrosoft.com/resource/subscriptions/3f7e29ba-24e0-42f6-8d9c-5149a14bda37/resourceGroups/AAPMarketplaceGroupsk/providers/Microsoft.Solutions/applications/AAPTestWIsk/overview) with billing enabled

image

**Comment by bhavenst** [comment]
@sharvarikhedkar No new hosts to bill here, so it didn't go through the full sequence..  I mentioned that you need to execution enough hosts to exceed the base quantity, but also I guess if that has been done prior and they are already billed then you need to create/run more. :)

Alternatively you can connect to the billing database and clear the billing_billedhosts table and run again..

If you are not using the offer I mentioned, I don't know what the base_quantity is set to, but if it's really high it might be hard to reach.

**Comment by sharvarikhedkar** [comment]
@bhavenst created a test vm, ran a demo job on that VM through controller of the deployment
and retested the PR, billing looks to be working as expected.

[UPDATE] removed the attachment to avoid any sensitive data leak.

**Review by sharvarikhedkar — APPROVED** [review]
LGTM

**Pull request merged**
